const phrases = [
  { text: "The two most powerful warriors are patience and time." },
  { text: "Time is money." },
  { text: "Time waits for no one." },
  { text: "Better three hours too soon than a minute too late." },
  { text: "Lost time is never found again." },
  { text: "Time is the most valuable thing a man can spend." },
  { text: "Time is the wisest counselor of all." },
  { text: "The key is in not spending time, but in investing it." },
  { text: "It is the time you have wasted for your rose that makes your rose so important." },
  { text: "Punctuality is the thief of time." },
  { text: "The trouble is, you think you have time." },
  { text: "Time is a cruel thief to rob us of our former selves. We lose as much to life as we do to death." }, 
  { text: "Suspect each moment, for it is a thief, tiptoeing away with more than it brings." },
  { text: "Time brings all things to pass." },
  { text: "Men talk of killing time, while time quietly kills them" },
  { text: "The future is uncertain but the end is always near." },
  { text: "Time takes it all, whether you want it to or not" },
  { text: "Time is a storm in which we are all lost" },
  { text: "Time is an illusion" },
  { text: "Time flies over us, but leaves its shadow behind." },
  { text: "Regret for wasted time is more wasted time." },
  { text: "You can’t make up for lost time. You can only do better in the future." },
  { text: "There’s never enough time to do all the nothing you want." },
  { text: "The time I kill is killing me" },
  { text: "Either you run the day, or the day runs you." },
  { text: "Your time is limited, so don’t waste it living someone else’s life" },
  { text: "They always say time changes things, but you actually have to change them yourself." },
  { text: "We must use time as a tool, not as a crutch" },
  { text: "If we take care of the moments, the years will take care of themselves" },
  { text: "All we have to decide is what to do with the time that is given us" },
  { text: "If time travel is possible, where are the tourists from the future?" },
  { text: "Time is the longest distance between two places" }
]

export default phrases;